// Command mdscript extracts a single shell script from a Markdown document,
// so that the commands a reader follows and the commands CI runs are the same
// text rather than two copies of it.
//
// It exists for docs/quickstart.md. A quickstart that CI cannot run goes
// stale silently — the reader is the only one who finds out, and by then they
// have given up. A quickstart kept in a separate script that the document
// merely describes goes stale the same way, one step further from the reader:
// CI proves the script, and the reader pastes the prose.
//
// Three kinds of fenced block are recognised:
//
//	```sh                          pasted into the script verbatim
//	```<lang> title=<path>         written to <path>, literally
//	```<lang> title=<path> expand  written to <path>, shell expansion applied
//
// Every other block is ignored, which is what lets the document carry
// expected output, error messages, and alternatives without them becoming
// script.
//
// A title= block is literal by default because the shell's expansion rules do
// not stop at the values an author meant to substitute. Measured against a
// document built from this repository's own configuration prose: a backtick
// in a YAML comment ran as a command, a token containing `$$` became the
// shell's process id, and a line ending in a backslash joined itself to the
// heredoc terminator and swallowed the block that followed. All three exited
// zero and produced a file the connector accepted. `expand` is opt-in so that
// a block pays for expansion only when it needs it — which, in the quickstart,
// is the roster and the two configurations, each of which embeds a key or an
// address computed by an earlier step.
package main

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"strings"
)

// heredocDelimiter terminates every file-writing block. The literal form
// quotes it, which is what makes those blocks literal; the expanding form
// does not.
const heredocDelimiter = "EOF"

func main() {
	if err := run(os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, "mdscript:", err)
		os.Exit(1)
	}
}

// blockMode is what the current fenced block contributes to the script.
type blockMode int

const (
	skip blockMode = iota
	verbatim
	literalFile
	expandedFile
)

func run(args []string) error {
	if len(args) != 2 {
		return fmt.Errorf("usage: mdscript <document.md> <script.sh>")
	}
	in, err := os.Open(args[0])
	if err != nil {
		return err
	}
	defer in.Close()

	script, shape, err := extract(args[0], in)
	if err != nil {
		return err
	}

	// Reported so a CI log records the shape of the document that ran, not
	// because anything is asserted about it. What a reader has to do is
	// bounded by review, not by a threshold: a number held here would only
	// ever be raised to match whatever the document had grown into.
	fmt.Fprintf(os.Stderr, "mdscript: %s -> %s (command blocks: %d, file blocks: %d, of which expanding: %d)\n",
		args[0], args[1], shape.commands, shape.files, shape.expansions)
	return os.WriteFile(args[1], []byte(script), 0o755)
}

// shape counts what the document contributed, for the log line only.
type shape struct {
	commands   int
	files      int
	expansions int
}

// extract assembles the script from doc. name appears in error messages so a
// refusal names the file and line a reader has to go and look at.
func extract(name string, doc io.Reader) (string, shape, error) {
	var (
		out   strings.Builder
		sh    shape
		block blockMode
		fence string
		line  int
	)
	out.WriteString("# Generated by cmd/mdscript from " + name + ". Do not edit.\n")

	sc := bufio.NewScanner(doc)
	sc.Buffer(make([]byte, 0, 1<<20), 1<<20)

	inBlock := false
	for sc.Scan() {
		line++
		text := sc.Text()

		if !inBlock {
			f, info, ok := openFence(text)
			if !ok {
				continue
			}
			inBlock, fence = true, f
			lang, title, expand := parseInfo(info)
			switch {
			case title != "" && expand:
				block = expandedFile
				sh.files, sh.expansions = sh.files+1, sh.expansions+1
				out.WriteString("cat > " + title + " <<" + heredocDelimiter + "\n")
			case title != "":
				block = literalFile
				sh.files++
				out.WriteString("cat > " + title + " <<'" + heredocDelimiter + "'\n")
			case lang == "sh":
				block = verbatim
				sh.commands++
			default:
				block = skip
			}
			continue
		}

		if closesFence(text, fence) {
			if block == literalFile || block == expandedFile {
				out.WriteString(heredocDelimiter + "\n")
			}
			inBlock, block = false, skip
			continue
		}

		switch block {
		case literalFile, expandedFile:
			// A body line that is exactly the terminator ends the heredoc
			// early and leaves the rest of the block running as shell.
			if strings.TrimRight(text, " \t") == heredocDelimiter {
				return "", sh, fmt.Errorf("%s:%d: a file block contains a line that is exactly %s",
					name, line, heredocDelimiter)
			}
			// Only in an expanding block: a trailing backslash escapes the
			// newline, so the last line of the block joins the terminator and
			// the heredoc never ends. A literal block leaves the backslash
			// alone, which is why this is not checked there.
			if block == expandedFile && strings.HasSuffix(text, `\`) {
				return "", sh, fmt.Errorf("%s:%d: a line in an expanding file block ends with a backslash, which would escape the heredoc terminator",
					name, line)
			}
			out.WriteString(text + "\n")
		case verbatim:
			out.WriteString(text + "\n")
		}
	}
	if err := sc.Err(); err != nil {
		return "", sh, err
	}
	if inBlock {
		return "", sh, fmt.Errorf("%s: unterminated fenced block", name)
	}
	return out.String(), sh, nil
}

// openFence reports whether text opens a fenced block, returning the fence
// run and the info string that followed it.
func openFence(text string) (fence, info string, ok bool) {
	t := strings.TrimLeft(text, " ")
	n := 0
	for n < len(t) && t[n] == '`' {
		n++
	}
	if n < 3 {
		return "", "", false
	}
	return t[:n], strings.TrimSpace(t[n:]), true
}

// closesFence reports whether text is a bare run of backticks at least as
// long as the fence that opened the block.
func closesFence(text, fence string) bool {
	t := strings.TrimSpace(text)
	return t != "" && len(t) >= len(fence) && strings.Trim(t, "`") == ""
}

// parseInfo splits an info string into its language, its title= value, and
// whether it asked for expansion.
func parseInfo(info string) (lang, title string, expand bool) {
	for i, f := range strings.Fields(info) {
		switch {
		case f == "expand":
			expand = true
		case strings.HasPrefix(f, "title="):
			title = strings.TrimPrefix(f, "title=")
		case i == 0:
			lang = f
		}
	}
	return lang, title, expand
}
